# Support Inkcast and future projects
buy_me_a_coffee: cobasi

# Uncomment when you apply for GitHub Sponsors:
# github: chizkidd

# Uncomment if you launch a premium tier later:
# custom: ["https://getinkcast.com/pro"]